DROP DATABASE IF EXISTS MensSiteDB;

CREATE DATABASE MensSiteDB;

USE MensSiteDB;

-- CREATE TABLE users (
--   `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   `email` VARCHAR(100) NOT NULL UNIQUE
-- );
CREATE TABLE users (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `name` VARCHAR(50) NOT NULL,
  `pic` VARCHAR(255) NULL,
  `bio` VARCHAR(255) NULL,
  `age` INT NULL
);

